--0311 평가시험

SELECT SUBSTR(EMAIL, INSTR(EMAIL,'@')+1) "DOMAIN"
     , COUNT(*) "EA"
     , SUM(COUNT(*)) OVER() "SUM_DOMAIN"
     , COUNT(*) / SUM(COUNT(*)) OVER() * 100 "%"
  FROM PROFESSOR
 GROUP BY SUBSTR(EMAIL, INSTR(EMAIL,'@')+1)
 ORDER BY 1;